"""
THE MAKE-OR-BREAK TEST, on real text with real embeddings.

The kernel method assumes:

    log P(agent produces answer a | truth is s)  =  alpha + beta * sim(a, s)

Two things have to be true for that to be worth anything:

  (G) GEOMETRY  -- wrong answers that models/humans actually produce must sit
      CLOSER to the truth in embedding space than arbitrary text. If errors are
      scattered uniformly, similarity carries no signal and the kernel is useless.

  (L) LOG-LINEARITY -- the log-odds that an answer is actually produced must fall
      roughly LINEARLY in similarity-to-truth. This is the specific functional
      form; if the real curve is flat, or a step, the aggregator is misspecified.

Data (both real, no synthetic anything):
  * TruthfulQA  -- per question: a best answer, several CORRECT paraphrases, and
                   several INCORRECT answers written as plausible misconceptions.
                   Tests (G) with human-curated plausible errors.
  * HaluEval QA -- per question: a right answer and a hallucinated answer that was
                   GENERATED BY A REAL MODEL (ChatGPT). Tests (G) and (L) against
                   genuine model error behaviour.

Embeddings: sentence-transformers all-MiniLM-L6-v2, cosine similarity.
"""
import io, json, os, sys
import numpy as np
import pandas as pd
import requests

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "data")
os.makedirs(CACHE, exist_ok=True)
OUT = os.path.join(HERE, "results")
FIG = os.path.join(OUT, "figures")

TQA = "https://huggingface.co/api/datasets/truthfulqa/truthful_qa/parquet/generation/validation/0.parquet"
HAL = "https://huggingface.co/api/datasets/pminervini/HaluEval/parquet/qa/data/0.parquet"


def fetch(url, name):
    p = os.path.join(CACHE, name)
    if not os.path.exists(p):
        print(f"  downloading {name} ...")
        r = requests.get(url, timeout=180); r.raise_for_status()
        open(p, "wb").write(r.content)
    df = pd.read_parquet(p)
    print(f"  {name}: {len(df)} rows, columns {list(df.columns)}")
    return df


def embedder():
    from sentence_transformers import SentenceTransformer
    m = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    def enc(texts):
        return m.encode(list(texts), batch_size=256, convert_to_numpy=True,
                        normalize_embeddings=True, show_progress_bar=False)
    return enc


def pct(a):
    a = np.asarray(a)
    return (f"n={len(a):6d}  mean {a.mean():.3f}  sd {a.std():.3f}  "
            f"p10 {np.percentile(a,10):.3f}  p50 {np.percentile(a,50):.3f}  p90 {np.percentile(a,90):.3f}")


RESULTS = {}

# =====================================================================
print("=" * 78)
print(" LOADING REAL DATA")
print("=" * 78)
tqa = fetch(TQA, "truthfulqa_generation.parquet")
hal = fetch(HAL, "halueval_qa.parquet")
print("\n  loading embedding model ...")
enc = embedder()
print("  ready.\n")


# =====================================================================
print("=" * 78)
print(" TEST G1  --  TruthfulQA: do the three tiers actually exist?")
print("=" * 78)
tqa = tqa[tqa["best_answer"].astype(bool)].reset_index(drop=True)
N = min(600, len(tqa))
sub = tqa.iloc[:N]

best = list(sub["best_answer"])
E_best = enc(best)

sim_para, sim_wrong, sim_rand = [], [], []
rng = np.random.default_rng(0)
for i in range(N):
    corr = [c for c in list(sub["correct_answers"].iloc[i]) if c and c != best[i]]
    wrong = [c for c in list(sub["incorrect_answers"].iloc[i]) if c]
    if corr:
        sim_para += list(enc(corr) @ E_best[i])
    if wrong:
        sim_wrong += list(enc(wrong) @ E_best[i])
    j = rng.integers(0, N)
    while j == i:
        j = rng.integers(0, N)
    other = [c for c in list(sub["incorrect_answers"].iloc[j]) if c][:2]
    if other:
        sim_rand += list(enc(other) @ E_best[i])

print(f"\n  similarity to the best answer:")
print(f"    CORRECT paraphrases      {pct(sim_para)}")
print(f"    INCORRECT (plausible)    {pct(sim_wrong)}")
print(f"    random answer, other Q   {pct(sim_rand)}")
gap = np.mean(sim_wrong) - np.mean(sim_rand)
print(f"\n    plausible-wrong sits {gap:+.3f} above random-wrong.")
print(f"    my synthetic pool assumed:  paraphrase 0.975 / near-wrong 0.75 / far 0.30")
RESULTS["G1_truthfulqa"] = dict(
    para=float(np.mean(sim_para)), wrong=float(np.mean(sim_wrong)), rand=float(np.mean(sim_rand)),
    para_sd=float(np.std(sim_para)), wrong_sd=float(np.std(sim_wrong)), rand_sd=float(np.std(sim_rand)),
    n_para=len(sim_para), n_wrong=len(sim_wrong), n_rand=len(sim_rand))


# =====================================================================
print("\n" + "=" * 78)
print(" TEST G2  --  HaluEval: do REAL MODEL errors land near the truth?")
print("=" * 78)
hal = hal.dropna(subset=["right_answer", "hallucinated_answer"]).reset_index(drop=True)
Nh = min(4000, len(hal))
h = hal.iloc[:Nh]
E_right = enc(h["right_answer"])
E_hall = enc(h["hallucinated_answer"])

s_model_err = np.einsum("ij,ij->i", E_hall, E_right)          # model's own wrong answer
perm = rng.permutation(Nh)
perm[perm == np.arange(Nh)] = (perm[perm == np.arange(Nh)] + 1) % Nh
s_random = np.einsum("ij,ij->i", E_hall[perm], E_right)       # someone else's wrong answer

print(f"\n  similarity to the right answer:")
print(f"    the model's OWN wrong answer     {pct(s_model_err)}")
print(f"    another question's wrong answer  {pct(s_random)}")
d = s_model_err.mean() - s_random.mean()
pooled = np.sqrt((s_model_err.var() + s_random.var()) / 2)
print(f"\n    difference {d:+.3f}   Cohen's d = {d/pooled:.2f}")
frac = float((s_model_err > s_random).mean())
print(f"    the model's own error is nearer the truth in {100*frac:.1f}% of questions")
RESULTS["G2_halueval"] = dict(model_err=float(s_model_err.mean()), random=float(s_random.mean()),
                              cohens_d=float(d/pooled), frac_nearer=frac, n=int(Nh))


# =====================================================================
print("\n" + "=" * 78)
print(" TEST L  --  is log-odds(produced) LINEAR in similarity?")
print("=" * 78)
print("""
  Case-control design. POSITIVES are answers a real model actually produced
  (HaluEval hallucinations). CONTROLS are answers it did not produce, drawn from
  other questions so they span a wide similarity range. Bin by similarity to the
  truth and look at the log-odds of being a real model output in each bin.
  Under the model, that curve should be a straight line with slope beta.
""")
K_CTRL = 8
pos_sim, ctrl_sim = s_model_err, []
for k in range(K_CTRL):
    p = rng.permutation(Nh)
    p[p == np.arange(Nh)] = (p[p == np.arange(Nh)] + 1) % Nh
    ctrl_sim.append(np.einsum("ij,ij->i", E_hall[p], E_right))
ctrl_sim = np.concatenate(ctrl_sim)

edges = np.quantile(np.concatenate([pos_sim, ctrl_sim]), np.linspace(0.02, 0.98, 11))
centres, logodds, npos_l, nctl_l = [], [], [], []
for lo, hi in zip(edges[:-1], edges[1:]):
    npos = int(((pos_sim >= lo) & (pos_sim < hi)).sum())
    nctl = int(((ctrl_sim >= lo) & (ctrl_sim < hi)).sum())
    if npos >= 5 and nctl >= 5:
        centres.append((lo + hi) / 2)
        logodds.append(np.log(npos / nctl) + np.log(K_CTRL))   # offset for control multiplicity
        npos_l.append(npos); nctl_l.append(nctl)
centres, logodds = np.array(centres), np.array(logodds)

slope, intercept = np.polyfit(centres, logodds, 1)
pred = slope * centres + intercept
ss_res = ((logodds - pred) ** 2).sum()
ss_tot = ((logodds - logodds.mean()) ** 2).sum()
r2 = 1 - ss_res / ss_tot
# quadratic, to see whether curvature is really needed
q = np.polyfit(centres, logodds, 2)
r2q = 1 - ((logodds - np.polyval(q, centres)) ** 2).sum() / ss_tot

print(f"  {'sim bin centre':>16}{'n produced':>13}{'n control':>11}{'log-odds':>11}")
print("  " + "-" * 51)
for c, lo_, np_, nc_ in zip(centres, logodds, npos_l, nctl_l):
    print(f"  {c:>16.3f}{np_:>13d}{nc_:>11d}{lo_:>11.2f}")

print(f"\n  straight-line fit:  log-odds = {slope:.2f} * sim + {intercept:.2f}")
print(f"    R^2 (linear)     {r2:.3f}")
print(f"    R^2 (quadratic)  {r2q:.3f}   <- extra curvature buys {r2q-r2:+.3f}")
print(f"\n  The fitted slope IS beta. Estimated beta for this model: {slope:.2f}")
RESULTS["L_loglinear"] = dict(slope=float(slope), intercept=float(intercept),
                              r2_linear=float(r2), r2_quad=float(r2q),
                              centres=centres.tolist(), logodds=logodds.tolist(),
                              npos=npos_l, nctl=nctl_l)

# =====================================================================
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, (a1, a2) = plt.subplots(1, 2, figsize=(12.4, 4.8))
bins = np.linspace(-0.2, 1.0, 45)
a1.hist(sim_rand, bins=bins, alpha=0.62, label="random answer, different question", color="#9aa0a6", density=True)
a1.hist(sim_wrong, bins=bins, alpha=0.62, label="plausible WRONG answer (same question)", color="#e8871a", density=True)
a1.hist(sim_para, bins=bins, alpha=0.62, label="CORRECT paraphrase", color="#0b8043", density=True)
a1.set_xlabel("cosine similarity to the correct answer"); a1.set_ylabel("density")
a1.set_title("Real answer geometry (TruthfulQA)\nthe three tiers exist, but they OVERLAP heavily", fontsize=11)
a1.legend(fontsize=8); a1.grid(alpha=0.25)

a2.plot(centres, logodds, "o", color="#1a73e8", ms=8, label="observed")
xs = np.linspace(centres.min(), centres.max(), 100)
a2.plot(xs, slope * xs + intercept, "-", color="#0b8043", lw=2,
        label=f"straight line (R²={r2:.2f})")
a2.plot(xs, np.polyval(q, xs), "--", color="#b3261e", lw=1.4, label=f"quadratic (R²={r2q:.2f})")
a2.set_xlabel("cosine similarity to the truth"); a2.set_ylabel("log-odds the answer was really produced")
a2.set_title("Is the assumed law real? (HaluEval, model-generated errors)\n"
             f"slope = beta = {slope:.2f}", fontsize=11)
a2.legend(fontsize=8); a2.grid(alpha=0.25)
fig.tight_layout(); fig.savefig(os.path.join(FIG, "R1_real_data_test.png"), dpi=150, facecolor="white")
print("\n  [figure] results/figures/R1_real_data_test.png")

json.dump(RESULTS, open(os.path.join(OUT, "real_data_results.json"), "w"), indent=2)
print("  [json]   results/real_data_results.json")
