"""
Generate docs/ENSEMBLE_ANALYSIS.md from the cached per-ensemble results.

Requested at the 21 Aug meeting: "compute the same metrics on every single
ensemble from n=3 to n=6, put it in a doc so I can look through it properly."

Reads results/rank_crossover.json (210 QAMPARI ensembles) and
results/asqa_ensembles.json (42 ASQA ensembles). Pure formatting -- no
recomputation, so the numbers are exactly what the analysis modules produced.

Usage:  ./venv/bin/python -m open_ended_aggregation.analysis.make_ensemble_doc
"""
import json, math, statistics, collections

from open_ended_aggregation.paths import RESULTS, ROOT

SHORT = {"grok-4.3": "grok", "Kimi-K2.5": "Kimi", "MAI-Thinking-1": "MAI",
         "DeepSeek-V4-Flash": "DeepSk", "Cohere-command-a-plus-05-2026": "Cohere",
         "gpt-5.4-nano": "nano", "gpt-5.4-mini": "mini", "gpt-5.4": "gpt5.4"}


def s(m):
    return SHORT.get(m, m)


def corr(xs, ys):
    mx, my = statistics.mean(xs), statistics.mean(ys)
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    den = math.sqrt(sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys))
    return num / den if den else 0.0


def main():
    Q = json.load(open(RESULTS / "rank_crossover.json"))
    try:
        A = json.load(open(RESULTS / "asqa_ensembles.json"))
    except FileNotFoundError:
        A = []
    try:
        SC = json.load(open(RESULTS / "asc_ensembles.json"))
        ASCMAP = {(r["k"], frozenset(r["ens"])): r for r in SC["ensembles"]}
        ASCFULL, ASCTAU = SC["full_pool"], SC["tau"]
    except FileNotFoundError:
        ASCMAP, ASCFULL, ASCTAU = {}, None, None

    def asc_of(r):
        e = ASCMAP.get((r["k"], frozenset(r["ens"])))
        return e["asc"] if e else None

    out = []
    w = out.append
    w("# Ensemble analysis — every ensemble, n=3 to n=6\n")
    w("Requested 21 Aug. All numbers are cross-fitted (2-fold over questions, "
      "seed 0); weights, logistic coefficients, the pattern lookup, the gold-count "
      "regression and the keep threshold are fitted on the training half only. "
      "Generated by `analysis/make_ensemble_doc.py` from cached results — no "
      "recomputation.\n")
    w("**Two baselines.** `count` = MA-count: keep a claim if ≥θ *agents* assert "
      "it, exact string match, one vote per agent, θ cross-fitted on F1. This is "
      "the team's proposed naive multi-agent method, not a published one. "
      "`ASC` = the published pipeline (arXiv:2405.13131): edit-distance "
      "clustering at a tuned τ, strength = count of cluster *members* (not "
      "deduplicated per agent), θ tuned on a validation half to maximise F1-5, "
      "representative = first member. The two differ on three axes — exact match "
      "vs edit-distance clustering, per-agent dedup vs raw member counts, and F1 "
      "vs F1-5 as the tuning objective — so ASC is a separate arm, not a "
      "relabelling of counting.\n")
    if ASCTAU is not None:
        w(f"ASC's one unavoidable substitution: published ASC draws m≈50 stochastic "
          f"samples from ONE model; the cache holds one response per agent, so the "
          f"m samples are replaced by the n agents (this is exactly the extension "
          f"the team proposes). The LLM composition step is omitted — it costs API "
          f"calls and applies equally to every arm. τ tuned to **{ASCTAU}**, "
          f"full-pool ASC = **{ASCFULL['f1']:.2f}** F1 / {ASCFULL['f15']:.2f} F1-5.\n")
    if ASCMAP:
        f15 = [r["asc_f15"] for r in ASCMAP.values()]
        ft = [r.get("asc_f1tuned") for r in ASCMAP.values()]
        ft = [x for x in ft if x is not None]
        av = [r["asc"] for r in ASCMAP.values()]
        w(f"**Fairness check on ASC.** ASC tunes θ on **F1-5** (the paper's own "
          f"objective) while every arm here is compared on **F1**, which could "
          f"handicap it. Re-tuning ASC's θ on F1 instead moves it from "
          f"{statistics.mean(av):.2f} to {statistics.mean(ft):.2f} averaged over "
          f"all 210 ensembles — i.e. essentially not at all (identical at n=4,5,6; "
          f"+0.5 at n=3). So ASC trailing counting on F1 is a real property of the "
          f"method, not an artefact of the tuning objective. ASC's F1-5 is "
          f"{statistics.mean(f15):.2f} and is reported in the JSON.\n")
    w("**Other arms.** `best single` = strongest agent in that ensemble. "
      "`weighted` = marginal reliability weighting. `pattern` = shrunk "
      "`P(correct | exact subset asserting)`, which upper-bounds every rule that "
      "reads only who asserted. `rank+budget` = our method.\n")
    w("---\n")

    # ---------- headline: metric vs ensemble size
    w("## 1. Metric vs ensemble size — QAMPARI (set F1, 777 questions)\n")
    w("| n | ensembles | best single | ASC *(baseline 1)* | count *(baseline 2)* | weighted | pattern | rank+budget *(ours)* |")
    w("|---|---|---|---|---|---|---|---|")
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        av = [asc_of(r) for r in R]
        av = [x for x in av if x is not None]
        acell = f"{statistics.mean(av):.2f}" if av else "—"
        w(f"| **{k}** | {len(R)} | {statistics.mean(r['best'] for r in R):.2f} | "
          f"{acell} | "
          f"{statistics.mean(r['count'] for r in R):.2f} | "
          f"{statistics.mean(r['weighted'] for r in R):.2f} | "
          f"{statistics.mean(r['pattern'] for r in R):.2f} | "
          f"**{statistics.mean(r['rank+budget'] for r in R):.2f}** |")
    w("")
    w("Same table as gains over counting, which is how the trends read most clearly:\n")
    w("| n | vs ASC | vs count | ours − ASC | ours − count | ours vs count, % |")
    w("|---|---|---|---|---|---|")
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        c = statistics.mean(r["count"] for r in R)
        av = [asc_of(r) for r in R]; av = [x for x in av if x is not None]
        am = statistics.mean(av) if av else float("nan")
        o = statistics.mean(r["rank+budget"] for r in R)
        w(f"| **{k}** | {am:.2f} | {c:.2f} | **{o-am:+.2f}** | **{o-c:+.2f}** | "
          f"**{100*(o-c)/c:+.1f}%** |")
    w("")
    w("**Reading it.** Counting *improves* with n (22.15 → 27.74) because more "
      "agents make the support count a sharper filter. Reliability weighting "
      "*decays* and goes negative by n=6 — the published crossover. `rank+budget` "
      "stays ahead at every size, and its relative gain is largest where the pool "
      "is smallest.\n")
    w("Ensembles where each arm **significantly** beats counting "
      "(paired bootstrap over questions):\n")
    w("| n | weighted | pattern | rank | rank+budget |")
    w("|---|---|---|---|---|")
    tot = collections.Counter()
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        cells = []
        for a in ("weighted", "pattern", "rank", "rank+budget"):
            c = sum(1 for r in R if r.get(f"{a}_sig") and r.get(f"{a}_vs_cnt", 0) > 0)
            tot[a] += c; tot[f"{a}_n"] += len(R)
            cells.append(f"{c}/{len(R)}")
        w(f"| **{k}** | " + " | ".join(cells) + " |")
    w("| **total** | " + " | ".join(
        f"**{tot[a]}/{tot[f'{a}_n']}**"
        for a in ("weighted", "pattern", "rank", "rank+budget")) + " |")
    w("")

    xs = [r["dominance"] for r in Q]
    w(f"Correlation of relative dominance (best / mean of the rest) with each "
      f"arm's gain over counting, across all {len(Q)} ensembles:\n")
    w("| arm | corr with dominance |")
    w("|---|---|")
    for a in ("weighted", "pattern", "rank", "rank+budget"):
        w(f"| {a} | {corr(xs, [r[a] - r['count'] for r in Q]):+.3f} |")
    w("")
    w("---\n")

    # ---------- full listing
    w("## 2. Every QAMPARI ensemble\n")
    w("Sorted within each size by `rank+budget`. `Δcnt` and `Δbest` are our "
      "method's gain over counting and over the best single agent. "
      "`*` = significantly beats counting.\n")
    for k in (3, 4, 5, 6):
        R = sorted([r for r in Q if r["k"] == k],
                   key=lambda r: -r["rank+budget"])
        if not R:
            continue
        w(f"### n = {k} — {len(R)} ensembles\n")
        w("| # | agents | best single | ASC | count | weighted | rank+budget | Δcnt | ΔASC | Δbest |")
        w("|---|---|---|---|---|---|---|---|---|---|")
        for i, r in enumerate(R, 1):
            star = "*" if r.get("rank+budget_sig") and r.get("rank+budget_vs_cnt", 0) > 0 else ""
            av = asc_of(r)
            acell = f"{av:.2f}" if av is not None else "—"
            adel = f"{r['rank+budget']-av:+.2f}" if av is not None else "—"
            w(f"| {i} | {' + '.join(s(m) for m in r['ens'])} | "
              f"{r['best']:.2f} | {acell} | {r['count']:.2f} | {r['weighted']:.2f} | "
              f"**{r['rank+budget']:.2f}** | "
              f"{r['rank+budget']-r['count']:+.2f}{star} | {adel} | "
              f"{r['rank+budget']-r['best']:+.2f} |")
        w("")

    # ---------- ASQA
    if A:
        w("---\n")
        w("## 3. ASQA — every ensemble (DR*, 400 questions)\n")
        w("The rank/budget arms were not run per-ensemble on ASQA (the budget "
          "does not transfer there — see the weighting sweep doc). This is "
          "counting vs reliability weighting only.\n")
        w("| n | ensembles | best single | count | weighted | wgt − cnt | cnt − best |")
        w("|---|---|---|---|---|---|---|")
        for k in (3, 4, 5, 6):
            R = [r for r in A if r["k"] == k]
            if not R:
                continue
            w(f"| **{k}** | {len(R)} | {statistics.mean(r['best'] for r in R):.2f} | "
              f"{statistics.mean(r['count'] for r in R):.2f} | "
              f"{statistics.mean(r['weighted'] for r in R):.2f} | "
              f"**{statistics.mean(r['wgt_vs_cnt'] for r in R):+.2f}** | "
              f"{statistics.mean(r['cnt_vs_best'] for r in R):+.2f} |")
        w("")
        w("**This is the opposite trend to QAMPARI.** On ASQA weighting's gain "
          "over counting *grows* with ensemble size (+0.83 → +2.74) while "
          "counting falls further behind the best single agent (−0.70 → −2.26). "
          "The crossover does not replicate; it reverses.\n")
        for k in (3, 4, 5, 6):
            R = sorted([r for r in A if r["k"] == k], key=lambda r: -r["weighted"])
            if not R:
                continue
            w(f"### ASQA, n = {k} — {len(R)} ensembles\n")
            w("| # | agents | best single | count | weighted | wgt − cnt |")
            w("|---|---|---|---|---|---|")
            for i, r in enumerate(R, 1):
                star = "*" if r.get("wgt_cnt_sig") and r.get("wgt_vs_cnt", 0) > 0 else ""
                w(f"| {i} | {' + '.join(s(m) for m in r['ens'])} | "
                  f"{r['best']:.2f} | {r['count']:.2f} | **{r['weighted']:.2f}** | "
                  f"{r['wgt_vs_cnt']:+.2f}{star} |")
            w("")

    path = ROOT / "docs" / "ENSEMBLE_ANALYSIS.md"
    path.write_text("\n".join(out))
    print(f"  wrote {path}  ({len(out)} lines, "
          f"{len(Q)} QAMPARI + {len(A)} ASQA ensembles)")


if __name__ == "__main__":
    main()
