"""
Generate docs/ENSEMBLE_ANALYSIS.md from the cached per-ensemble results.

Requested at the 21 Aug meeting: "compute the same metrics on every single
ensemble from n=3 to n=6, put it in a doc so I can look through it properly."

Reads results/rank_crossover.json (210 QAMPARI ensembles) and
results/asqa_ensembles.json (42 ASQA ensembles). Pure formatting -- no
recomputation, so the numbers are exactly what the analysis modules produced.

Usage:  ./venv/bin/python -m open_ended_aggregation.analysis.make_ensemble_doc
"""
import json, math, statistics, collections

from open_ended_aggregation.paths import RESULTS, ROOT

SHORT = {"grok-4.3": "grok", "Kimi-K2.5": "Kimi", "MAI-Thinking-1": "MAI",
         "DeepSeek-V4-Flash": "DeepSk", "Cohere-command-a-plus-05-2026": "Cohere",
         "gpt-5.4-nano": "nano", "gpt-5.4-mini": "mini", "gpt-5.4": "gpt5.4"}


def s(m):
    return SHORT.get(m, m)


def corr(xs, ys):
    mx, my = statistics.mean(xs), statistics.mean(ys)
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    den = math.sqrt(sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys))
    return num / den if den else 0.0


def main():
    Q = json.load(open(RESULTS / "rank_crossover.json"))
    try:
        A = json.load(open(RESULTS / "asqa_ensembles.json"))
    except FileNotFoundError:
        A = []

    out = []
    w = out.append
    w("# Ensemble analysis — every ensemble, n=3 to n=6\n")
    w("Requested 21 Aug. All numbers are cross-fitted (2-fold over questions, "
      "seed 0); weights, logistic coefficients, the pattern lookup, the gold-count "
      "regression and the keep threshold are fitted on the training half only. "
      "Generated by `analysis/make_ensemble_doc.py` from cached results — no "
      "recomputation.\n")
    w("**Arms.** `best single` = the strongest agent in that ensemble. "
      "`count` = MA-count (keep a claim if ≥θ agents assert it, θ cross-fitted). "
      "`weighted` = marginal reliability weighting. `pattern` = shrunk "
      "`P(correct | exact subset asserting)`, which upper-bounds every rule that "
      "reads only who asserted. `rank` = our scoring model. `rank+budget` = plus "
      "the per-question keep count.\n")
    w("---\n")

    # ---------- headline: metric vs ensemble size
    w("## 1. Metric vs ensemble size — QAMPARI (set F1, 777 questions)\n")
    w("| n | ensembles | best single | count | weighted | pattern | rank | rank+budget |")
    w("|---|---|---|---|---|---|---|---|")
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        w(f"| **{k}** | {len(R)} | {statistics.mean(r['best'] for r in R):.2f} | "
          f"{statistics.mean(r['count'] for r in R):.2f} | "
          f"{statistics.mean(r['weighted'] for r in R):.2f} | "
          f"{statistics.mean(r['pattern'] for r in R):.2f} | "
          f"{statistics.mean(r['rank'] for r in R):.2f} | "
          f"**{statistics.mean(r['rank+budget'] for r in R):.2f}** |")
    w("")
    w("Same table as gains over counting, which is how the trends read most clearly:\n")
    w("| n | weighted | pattern | rank | rank+budget | rank+budget as % |")
    w("|---|---|---|---|---|---|")
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        c = statistics.mean(r["count"] for r in R)
        g = statistics.mean(r["rank+budget"] for r in R) - c
        w(f"| **{k}** | {statistics.mean(r['weighted'] for r in R)-c:+.2f} | "
          f"{statistics.mean(r['pattern'] for r in R)-c:+.2f} | "
          f"{statistics.mean(r['rank'] for r in R)-c:+.2f} | "
          f"**{g:+.2f}** | **{100*g/c:+.1f}%** |")
    w("")
    w("**Reading it.** Counting *improves* with n (22.15 → 27.74) because more "
      "agents make the support count a sharper filter. Reliability weighting "
      "*decays* and goes negative by n=6 — the published crossover. `rank+budget` "
      "stays ahead at every size, and its relative gain is largest where the pool "
      "is smallest.\n")
    w("Ensembles where each arm **significantly** beats counting "
      "(paired bootstrap over questions):\n")
    w("| n | weighted | pattern | rank | rank+budget |")
    w("|---|---|---|---|---|")
    tot = collections.Counter()
    for k in (3, 4, 5, 6):
        R = [r for r in Q if r["k"] == k]
        if not R:
            continue
        cells = []
        for a in ("weighted", "pattern", "rank", "rank+budget"):
            c = sum(1 for r in R if r.get(f"{a}_sig") and r.get(f"{a}_vs_cnt", 0) > 0)
            tot[a] += c; tot[f"{a}_n"] += len(R)
            cells.append(f"{c}/{len(R)}")
        w(f"| **{k}** | " + " | ".join(cells) + " |")
    w("| **total** | " + " | ".join(
        f"**{tot[a]}/{tot[f'{a}_n']}**"
        for a in ("weighted", "pattern", "rank", "rank+budget")) + " |")
    w("")

    xs = [r["dominance"] for r in Q]
    w(f"Correlation of relative dominance (best / mean of the rest) with each "
      f"arm's gain over counting, across all {len(Q)} ensembles:\n")
    w("| arm | corr with dominance |")
    w("|---|---|")
    for a in ("weighted", "pattern", "rank", "rank+budget"):
        w(f"| {a} | {corr(xs, [r[a] - r['count'] for r in Q]):+.3f} |")
    w("")
    w("---\n")

    # ---------- full listing
    w("## 2. Every QAMPARI ensemble\n")
    w("Sorted within each size by `rank+budget`. `Δcnt` and `Δbest` are our "
      "method's gain over counting and over the best single agent. "
      "`*` = significantly beats counting.\n")
    for k in (3, 4, 5, 6):
        R = sorted([r for r in Q if r["k"] == k],
                   key=lambda r: -r["rank+budget"])
        if not R:
            continue
        w(f"### n = {k} — {len(R)} ensembles\n")
        w("| # | agents | best single | count | weighted | pattern | rank+budget | Δcnt | Δbest |")
        w("|---|---|---|---|---|---|---|---|---|")
        for i, r in enumerate(R, 1):
            star = "*" if r.get("rank+budget_sig") and r.get("rank+budget_vs_cnt", 0) > 0 else ""
            w(f"| {i} | {' + '.join(s(m) for m in r['ens'])} | "
              f"{r['best']:.2f} | {r['count']:.2f} | {r['weighted']:.2f} | "
              f"{r['pattern']:.2f} | **{r['rank+budget']:.2f}** | "
              f"{r['rank+budget']-r['count']:+.2f}{star} | "
              f"{r['rank+budget']-r['best']:+.2f} |")
        w("")

    # ---------- ASQA
    if A:
        w("---\n")
        w("## 3. ASQA — every ensemble (DR*, 400 questions)\n")
        w("The rank/budget arms were not run per-ensemble on ASQA (the budget "
          "does not transfer there — see the weighting sweep doc). This is "
          "counting vs reliability weighting only.\n")
        w("| n | ensembles | best single | count | weighted | wgt − cnt | cnt − best |")
        w("|---|---|---|---|---|---|---|")
        for k in (3, 4, 5, 6):
            R = [r for r in A if r["k"] == k]
            if not R:
                continue
            w(f"| **{k}** | {len(R)} | {statistics.mean(r['best'] for r in R):.2f} | "
              f"{statistics.mean(r['count'] for r in R):.2f} | "
              f"{statistics.mean(r['weighted'] for r in R):.2f} | "
              f"**{statistics.mean(r['wgt_vs_cnt'] for r in R):+.2f}** | "
              f"{statistics.mean(r['cnt_vs_best'] for r in R):+.2f} |")
        w("")
        w("**This is the opposite trend to QAMPARI.** On ASQA weighting's gain "
          "over counting *grows* with ensemble size (+0.83 → +2.74) while "
          "counting falls further behind the best single agent (−0.70 → −2.26). "
          "The crossover does not replicate; it reverses.\n")
        for k in (3, 4, 5, 6):
            R = sorted([r for r in A if r["k"] == k], key=lambda r: -r["weighted"])
            if not R:
                continue
            w(f"### ASQA, n = {k} — {len(R)} ensembles\n")
            w("| # | agents | best single | count | weighted | wgt − cnt |")
            w("|---|---|---|---|---|---|")
            for i, r in enumerate(R, 1):
                star = "*" if r.get("wgt_cnt_sig") and r.get("wgt_vs_cnt", 0) > 0 else ""
                w(f"| {i} | {' + '.join(s(m) for m in r['ens'])} | "
                  f"{r['best']:.2f} | {r['count']:.2f} | **{r['weighted']:.2f}** | "
                  f"{r['wgt_vs_cnt']:+.2f}{star} |")
            w("")

    path = ROOT / "docs" / "ENSEMBLE_ANALYSIS.md"
    path.write_text("\n".join(out))
    print(f"  wrote {path}  ({len(out)} lines, "
          f"{len(Q)} QAMPARI + {len(A)} ASQA ensembles)")


if __name__ == "__main__":
    main()
