"""
TRIPLE REPLICATION -- the same protocol on three INDEPENDENT open-ended datasets.

The point of this file is reliability. The earlier result came from one dataset,
one encoder and one control design, and the control design turned out to be doing
most of the work. Here the whole protocol is re-run on three datasets that share
no construction pipeline, with three encoders each, and with bootstrap confidence
intervals so every number has an error bar.

THE THREE DATASETS -- deliberately different in where the wrong answers come from:

  HaluEval QA    wrong answers GENERATED BY A MODEL (ChatGPT), HotpotQA questions.
                 The only source here that is literally model output.
  TruthfulQA     wrong answers written by EXPERTS as common human misconceptions,
                 adversarially chosen to fool models. Different domain, different era.
  SciQ           wrong answers written by CROWDWORKERS as exam distractors, school
                 science domain. Third construction pipeline entirely.

Only HaluEval is genuine model output. The other two test the weaker but still
necessary claim that PLAUSIBLE wrong answers sit where the model predicts. Stated
plainly rather than glossed.

THE CLAIM UNDER TEST

    log-odds( answer a is a plausible/produced wrong answer ) = alpha + beta * sim(a, truth)

and specifically whether the STRAIGHT-LINE form survives once controls are
topic-matched -- the regime an aggregator actually operates in, since it chooses
among answers to one and the same question.

Run:  ./venv/bin/python triple_replication.py
"""
import os, json
import numpy as np, pandas as pd, requests

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "data"); os.makedirs(CACHE, exist_ok=True)
OUT = os.path.join(HERE, "results"); FIG = os.path.join(OUT, "figures")

ENCODERS = ["sentence-transformers/all-MiniLM-L6-v2",
            "sentence-transformers/all-mpnet-base-v2",
            "BAAI/bge-small-en-v1.5"]
N_MAX = 3000
K_CTRL = 8
N_BOOT = 200
GRID = [1, 5, 50, 1000, "random"]

URLS = {
 "HaluEval-QA": "https://huggingface.co/api/datasets/pminervini/HaluEval/parquet/qa/data/0.parquet",
 "TruthfulQA":  "https://huggingface.co/api/datasets/truthfulqa/truthful_qa/parquet/generation/validation/0.parquet",
 "SciQ":        "https://huggingface.co/api/datasets/allenai/sciq/parquet/default/train/0.parquet",
}


def get(name):
    p = os.path.join(CACHE, f"{name}.parquet")
    if not os.path.exists(p):
        r = requests.get(URLS[name], timeout=300); r.raise_for_status(); open(p, "wb").write(r.content)
    return pd.read_parquet(p)


def load_pairs(name):
    """-> (truth_texts, wrong_texts, provenance)"""
    d = get(name)
    if name == "HaluEval-QA":
        d = d.dropna(subset=["right_answer", "hallucinated_answer"])
        t, w = d["right_answer"], d["hallucinated_answer"]
        prov = "model-generated (ChatGPT)"
    elif name == "TruthfulQA":
        d = d[d["best_answer"].astype(bool)]
        keep = d["incorrect_answers"].apply(lambda a: len(a) > 0 and bool(a[0]))
        d = d[keep]
        t, w = d["best_answer"], d["incorrect_answers"].apply(lambda a: a[0])
        prov = "expert-written misconceptions"
    else:
        d = d.dropna(subset=["correct_answer", "distractor1"])
        t, w = d["correct_answer"], d["distractor1"]
        prov = "crowdworker distractors"
    t, w = list(t)[:N_MAX], list(w)[:N_MAX]
    return t, w, prov


_enc = {}
def encode(model_name, texts):
    if model_name not in _enc:
        from sentence_transformers import SentenceTransformer
        _enc[model_name] = SentenceTransformer(model_name)
    return _enc[model_name].encode(list(texts), batch_size=128, convert_to_numpy=True,
                                   normalize_embeddings=True, show_progress_bar=False)


def fit(pos, ctl, k, nbins=10):
    allv = np.concatenate([pos, ctl])
    for nb, mc in [(nbins, 5), (8, 4), (6, 3), (5, 3)]:
        e = np.quantile(allv, np.linspace(0.02, 0.98, nb + 1))
        c, lo = [], []
        for a, b in zip(e[:-1], e[1:]):
            p = int(((pos >= a) & (pos < b)).sum()); q = int(((ctl >= a) & (ctl < b)).sum())
            if p >= mc and q >= mc:
                c.append((a + b) / 2); lo.append(np.log(p / q) + np.log(k))
        if len(c) >= 4:
            c, lo = np.array(c), np.array(lo)
            sl, ic = np.polyfit(c, lo, 1)
            sst = ((lo - lo.mean()) ** 2).sum()
            if sst <= 0: return None
            r2 = 1 - ((lo - (sl * c + ic)) ** 2).sum() / sst
            r2q = 1 - ((lo - np.polyval(np.polyfit(c, lo, 2), c)) ** 2).sum() / sst
            return dict(slope=float(sl), r2=float(r2), r2_quad=float(r2q), nbins=len(c))
    return None


def control_block(Ew, Et, order, r, k, rng):
    """Per-question control similarities, shape [n, k].

    Keeping controls as a [n, k] BLOCK (rather than a flat array) is what makes
    bootstrapping cheap: resampling questions is then just row indexing, with no
    need to recompute the nearest-neighbour structure.
    """
    n = len(Et)
    if r == "random":
        cols = []
        for _ in range(k):
            p = rng.permutation(n); s_ = p == np.arange(n); p[s_] = (p[s_] + 1) % n
            cols.append(np.einsum("ij,ij->i", Ew[p], Et))
        return np.stack(cols, axis=1)
    r = min(r, max(1, order.shape[1] - k))
    idx = order[:, (r - 1):(r - 1 + k)]
    return np.stack([np.einsum("ij,ij->i", Ew[idx[:, j]], Et) for j in range(k)], axis=1)


def boot_ci(pos, ctl_block, k, rng, nboot=N_BOOT):
    """Bootstrap over QUESTIONS -- pure row resampling, no re-embedding."""
    n = len(pos); sl, r2, r2q = [], [], []
    for _ in range(nboot):
        ii = rng.integers(0, n, n)
        f = fit(pos[ii], ctl_block[ii].ravel(), k)
        if f: sl.append(f["slope"]); r2.append(f["r2"]); r2q.append(f["r2_quad"])
    q = lambda a: (float(np.percentile(a, 2.5)), float(np.percentile(a, 97.5))) if len(a) > 10 else (float("nan"), float("nan"))
    return q(sl), q(r2), q(r2q)


RESULTS = {}
print("=" * 92)
print(" TRIPLE REPLICATION -- three independent datasets, three encoders, bootstrap CIs")
print("=" * 92)

for ds in URLS:
    t, w, prov = load_pairs(ds)
    RESULTS[ds] = dict(provenance=prov, n=len(t), encoders={})
    print(f"\n\n{'#'*92}\n# {ds}   n={len(t)}   wrong answers: {prov}\n{'#'*92}")
    for menc in ENCODERS:
        short = menc.split("/")[-1]
        Et, Ew = encode(menc, t), encode(menc, w)
        pos = np.einsum("ij,ij->i", Ew, Et)
        sim = Et @ Et.T; np.fill_diagonal(sim, -np.inf)
        order = np.argsort(-sim, axis=1)
        rng = np.random.default_rng(0)

        # effect size vs random controls
        ctl_rand = control_block(Ew, Et, order, "random", K_CTRL, np.random.default_rng(1)).ravel()
        cd = (pos.mean() - ctl_rand.mean()) / np.sqrt((pos.var() + ctl_rand.var()) / 2)

        print(f"\n  {short}   (Cohen's d vs random controls = {cd:.2f})")
        print(f"    {'controls':>10}{'beta':>8}{'R2 straight':>26}{'R2 curved':>26}")
        print("    " + "-" * 88)
        rows = {}
        for r in GRID:
            blk = control_block(Ew, Et, order, r, K_CTRL, np.random.default_rng(2))
            f = fit(pos, blk.ravel(), K_CTRL)
            if f is None:
                print(f"    {str(r):>10}{'--':>8}{'no fit':>26}{'':>26}"); continue
            bs, br, bq = boot_ci(pos, blk, K_CTRL, np.random.default_rng(3))
            print(f"    {str(r):>10}{f['slope']:>8.2f}"
                  f"{f['r2']:>14.3f}  [{br[0]:.2f},{br[1]:.2f}]"
                  f"{f['r2_quad']:>14.3f}  [{bq[0]:.2f},{bq[1]:.2f}]")
            rows[str(r)] = dict(f, ci_slope=bs, ci_r2=br, ci_r2q=bq)

        # placebo
        pool = np.concatenate([pos, control_block(Ew, Et, order, 1, K_CTRL, np.random.default_rng(4)).ravel()])
        rp = np.random.default_rng(5); ii = rp.permutation(len(pool))
        fp = fit(pool[ii[:len(pos)]], pool[ii[len(pos):]], K_CTRL)
        ok = fp is not None and abs(fp["slope"]) < 1.0
        print(f"    {'PLACEBO':>10}{fp['slope']:>8.2f}{fp['r2']:>14.3f}"
              f"{'':>12}{'PASS -- invents nothing' if ok else 'FAIL':>26}")
        rows["placebo"] = fp
        RESULTS[ds]["encoders"][short] = dict(cohens_d=float(cd), grid=rows)

# =====================================================================
print("\n\n" + "=" * 92)
print(" DOES THE PATTERN REPLICATE?")
print("=" * 92)
print("""
  Pattern claimed: under HARD (topic-matched) controls a STRAIGHT line fits badly,
  while allowing CURVATURE still fits well. If that holds in all 9 dataset x encoder
  cells, the conclusion is solid rather than a quirk of one corpus.
""")
print(f"  {'dataset':<14}{'encoder':<24}{'R2 straight (r=1)':>20}{'R2 curved (r=1)':>18}{'verdict':>16}")
print("  " + "-" * 92)
n_ok = n_tot = 0
for ds, D in RESULTS.items():
    for enc_name, E in D["encoders"].items():
        g = E["grid"].get("1")
        if not g: continue
        n_tot += 1
        curved_wins = g["r2_quad"] - g["r2"] > 0.15
        n_ok += curved_wins
        print(f"  {ds:<14}{enc_name:<24}{g['r2']:>20.3f}{g['r2_quad']:>18.3f}"
              f"{('curved wins' if curved_wins else 'both fit'):>16}")
print(f"\n  curvature required in {n_ok}/{n_tot} cells")
placebos = [E["grid"]["placebo"]["slope"] for D in RESULTS.values() for E in D["encoders"].values()
            if E["grid"].get("placebo")]
print(f"  placebo |beta| max across all cells: {max(abs(np.array(placebos))):.3f}  (must be ~0)")
json.dump(RESULTS, open(os.path.join(OUT, "triple_replication.json"), "w"), indent=2)
print("\n  -> results/triple_replication.json")
